//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "credit_book")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub nat_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::credit_payments::Entity")]
    CreditPayments,
    #[sea_orm(has_many = "super::order_credit::Entity")]
    OrderCredit,
}

impl Related<super::credit_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CreditPayments.def()
    }
}

impl Related<super::order_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderCredit.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
