//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;
use async_graphql::{ComplexObject, InputObject, SimpleObject};
use macros::FilterQueryBuilder;
use std::collections::HashMap;
use crate::entities::Paging;
use async_graphql::dataloader::{DataLoader, Loader};
use async_graphql::*;
use itertools::Itertools;
use sea_orm::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel,Eq,Hash,SimpleObject,Default)]
#[graphql(name="ItemToCar",complex)]
#[sea_orm(table_name = "item_car")]
pub struct Model {
    pub car_id: i32,
    pub item_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
}

#[derive(Clone, Debug, PartialEq,Eq,Hash,Default,InputObject,FilterQueryBuilder)]
#[graphql(name="ItemToCarInput")]
pub struct ModelInput {
    pub car_id: Option<i32>,
    pub item_id: Option<i32>,
    pub id: Option<i32>,
    pub page : Option<Paging>
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::items::Entity",
        from = "Column::ItemId",
        to = "super::items::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Items,
    #[sea_orm(
        belongs_to = "super::cars::Entity",
        from = "Column::CarId",
        to = "super::cars::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cars,
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Items.def()
    }
}

impl Related<super::cars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cars.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
