//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

pub mod prelude;

pub mod alter_names;
pub mod buy_history;
pub mod car_brands;
pub mod car_series;
pub mod cars;
pub mod credit_book;
pub mod credit_payments;
pub mod fourni;
pub mod item_car;
pub mod item_feedback;
pub mod item_order;
pub mod items;
pub mod order_credit;
pub mod orders;
pub mod part_brands;
pub mod part_names;
pub mod part_wishes;
pub mod place_history;
pub mod place_item;
pub mod place_locations;
pub mod places;
pub mod users;

pub struct Query;

impl Query {
    async fn names(&self)-> String{
        "hide".to_string()
    }
}
