//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub time: DateTime,
    pub paid: i32,
    pub took_it: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order_credit::Entity")]
    OrderCredit,
    #[sea_orm(has_many = "super::item_order::Entity")]
    ItemOrder,
}

impl Related<super::order_credit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderCredit.def()
    }
}

impl Related<super::item_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItemOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
