//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "place_locations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::places::Entity")]
    Places,
}

impl Related<super::places::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Places.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
