//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

pub use super::alter_names::Entity as AlterNames;
pub use super::buy_history::Entity as BuyHistory;
pub use super::car_brands::Entity as CarBrands;
pub use super::car_series::Entity as CarSeries;
pub use super::cars::Entity as Cars;
pub use super::credit_book::Entity as CreditBook;
pub use super::credit_payments::Entity as CreditPayments;
pub use super::fourni::Entity as Fourni;
pub use super::item_car::Entity as ItemCar;
pub use super::item_feedback::Entity as ItemFeedback;
pub use super::item_order::Entity as ItemOrder;
pub use super::items::Entity as Items;
pub use super::order_credit::Entity as OrderCredit;
pub use super::orders::Entity as Orders;
pub use super::part_brands::Entity as PartBrands;
pub use super::part_names::Entity as PartNames;
pub use super::part_wishes::Entity as PartWishes;
pub use super::place_history::Entity as PlaceHistory;
pub use super::place_item::Entity as PlaceItem;
pub use super::place_locations::Entity as PlaceLocations;
pub use super::places::Entity as Places;
pub use super::users::Entity as Users;
