[package]
name = "macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0"
syn = "1.0.84"
itertools = "0.10.3"
proc-macro2 = "1.0.36"
convert_case = "0.5.0"
[lib]
proc-macro = true
